### ISSUE TITLE
확인이 불가능합니다

### ISSUE THREAD

**Issue by chldbst** [joyfuI/NaverCafePass#10]
https://cafe.naver.com/sevennest/104126 < 카페 회원가입을하고 등업을해야 게시글들을 볼수가있습니다

**Comment by joyfuI** [comment]
등업은 무리라서 해당 게시글 말고 따로 확인을 해봤는데요. 막힌거 같습니다.
모바일 페이지가 예전에 비슷한 방식으로 막혔었는데 이걸 pc에다가도 적용을 했네요.
주말에 자세히 확인해보고 우회 방법을 못 찾으면 이 확장은 이제 끝인 걸로...

**Comment by joyfuI** [comment]
리퍼러 체크에서 특정한 파라미터 체크로 방식이 바뀌었는데 파라미터 값이 암호화 되어 있어 뭐 어떻게 할 수가 없네요.
네이버 카페는 막힌게 맞습니다.
아직 다음 카페는 정상 작동하니 확장을 내리진 않을 예정입니다. (본격 이름과 실제가 다른 것...)
