### ISSUE TITLE
작동 안하는 게시물 링크입니다.

### ISSUE THREAD

**Issue by Muswc** [joyfuI/NaverCafePass#2]
https://cafe.naver.com/gtamasters

**Comment by Muswc** [comment]
아무래도 너무 이슈를 막 던진 것 같아서 다시 생각해봤는데, 카페에서 검색도 금지한 것 같습니다. 기존에는 전체공개였던 게시물이 바뀌면서 제가 착각한 것 같습니다. 제 게시물을 실험삼아 테스트한 결과 확장 프로그램은 정상 작동하는 것 같습니다. 혼동을 드려 죄송합니다.

**Comment by joyfuI** [comment]
아닙니다. 이슈 남겨주셔서 감사해요.ㅎ
