### ISSUE TITLE
네이버까페 - 

### ISSUE THREAD

**Issue by PeachKorea** [joyfuI/NaverCafePass#5]
고생이 많으십니다. 해당 사이트가 크롬에서 안됩니다 ㅠ.

https://cafe.naver.com/makemywedding/120824

**Comment by joyfuI** [comment]
흠.. 해당 링크를 크롬으로 들어가 봤는데요. 저 글은 전체 공개라 아예 확장 없이도 글 열람이 됩니다.
혹시나 해서 해당 카페의 다른 글도 테스트해봤는데 문제없이 작동합니다.
참고로 글에 검색 허용이 되어 있어야 이 확장으로 글을 볼 수 있습니다.

**Comment by PeachKorea** [comment]
안녕하세요? 빠른 답변 감사합니다. 제가 잘못된 예시를 소개 해드렸네요. 혹시 아래 url은 접근 가능하세요?https://cafe.naver.com/makemywedding/119952

아 그러니까, 회원공개이되, 네이버에서 검색 할 수 있는 option은 enable되어 있어야지 plug-in으로 redirection하는거군요?ㅠ

**Comment by PeachKorea** [comment]
아 같은 링크이군요 ㅠㅠ 접근이 안되다 보니 게시글 URL을 뽑을수가 없네요 ㅠㅋ

**Comment by PeachKorea** [comment]
https://cafe.naver.com/makemywedding/119952

**Comment by joyfuI** [comment]
네. 작동원리가 글 접속할 때 네이버 검색을 통해서 접속한 걸로 속여서 접속하는 거라 검색 허용이 안되어 있으면 안됩니다.
해당 글을 네이버에 검색해봤는데 검색결과가 안뜨는 걸로 봐서 검색 허용이 안돼있는 거 같습니다.
글제목: `가봉스냅데이 뮤제네프 헤메 후기쪄왔어요 (색조때문에 뮤제네프 고민하시는 분들 봐주세요☺️)`
